### ISSUE TITLE
wireguard配置已经生成, 但是启动后ip不通

### ISSUE THREAD

**Issue by marlonfan** [PinkD/corplink#1]
经过前面的配置和验证码输入登录后已经成功下发wireguard配置.

看了下wireguard所下发的路由表都是对的. 但是无法访问所下发的IP

**Comment by PinkD** [comment]
~~没想到我随便写的脚本真有人用~~  🤣 

1. 所下发的 IP 是指下发的路由表中的某个 IP 段中的某个 IP 吗？ ping 的话，你需要找到一个内网中不禁 ping 的机器才行，然后 `ip route get your_ip` 看看是不是走的 wireguard 的接口
2. `wg` 命令输出中 `latest handshake: 2 minutes, 1 second ago` 这一行是否正常？一般超过几分钟就不正常了，说明连接已经断了，需要重新登录

**Comment by marlonfan** [comment]
我检查了下，本地路由表创建也成功了，走的确实是wireguard的tun。感觉像是隧道建立失败了，其他貌似都是成功的。奇怪🤔不知道还有没有其他鉴权没过

**Comment by PinkD** [comment]
我有时候也遇到过，但是都是重新生成一套配置就好了，你可以试试，如果还是不行我也没办法了

**Comment by marlonfan** [comment]
> 我有时候也遇到过，但是都是重新生成一套配置就好了，你可以试试，如果还是不行我也没办法了

了解了. 感谢作者.  我也去抓包看看到底啥情况~  现有代码给了很好的参考  感谢~
